//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaplugaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentScheduling
    {
        public long AppointmentID { get; set; }
        public long UserID { get; set; }
        public long AddressID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long ScheduleID { get; set; }
    
        public virtual Addresses Addresses { get; set; }
        public virtual ScheduleAppointment ScheduleAppointment { get; set; }
        public virtual Users Users { get; set; }
    }
}
