//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaplugaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public long CartID { get; set; }
        public long MedicalImplementsID { get; set; }
        public int Quantity { get; set; }
        public long UserID { get; set; }
    
        public virtual MedicalImplements MedicalImplements { get; set; }
        public virtual Users Users { get; set; }
    }
}
