//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaplugaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailCurse
    {
        public long DetailCurseID { get; set; }
        public long MedicalCourseID { get; set; }
        public decimal PaidPrice { get; set; }
        public int PaidQuantity { get; set; }
        public decimal Tax { get; set; }
        public long MasterPurchaseCurseID { get; set; }
        public string PaymentStatus { get; set; }
    
        public virtual MasterPurchaseCurse MasterPurchaseCurse { get; set; }
        public virtual MedicalCourses MedicalCourses { get; set; }
    }
}
