//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaplugaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLogs
    {
        public long LogID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string ErrorMessage { get; set; }
        public string Source { get; set; }
        public string AdditionalInformation { get; set; }
        public long UserID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
