//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaplugaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterPurchaseCurse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterPurchaseCurse()
        {
            this.DetailCurse = new HashSet<DetailCurse>();
        }
    
        public long MasterPurchaseCurseID { get; set; }
        public long UserID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public decimal TotalPurchase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailCurse> DetailCurse { get; set; }
        public virtual Users Users { get; set; }
    }
}
