//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaplugaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registeredcourses
    {
        public long RegisteredcoursesID { get; set; }
        public long UserID { get; set; }
        public long MedicalCourseID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Registrationdate { get; set; }
    
        public virtual MedicalCourses MedicalCourses { get; set; }
        public virtual Users Users { get; set; }
    }
}
