//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaplugaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registeredcourses
    {
        public long RegisteredcoursesID { get; set; }
        public long UserID { get; set; }
        public long MedicalCourseID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Registrationdate { get; set; }
    
        public virtual MedicalCourses MedicalCourses { get; set; }
        public virtual Users Users { get; set; }
    }
}
